import { MetadataRoute } from 'next'

export const dynamic = 'force-static'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://ytsummarizer-blog.vercel.app'

  const posts = [
    'how-to-summarize-youtube-videos',
    'how-to-summarize-machine-learning-videos-with-ai',
    'python-tutorial-video-summary-learn-faster',
    'web-development-video-summaries-skip-to-what-matters',
    'data-science-video-summary-guide',
    'crypto-explained-video-summaries-made-simple',
    'digital-marketing-video-summary-tips',
    'productivity-hacks-summarize-youtube-videos-fast',
    'fitness-video-summaries-get-the-workout-plan-faster',
    'youtube-summarizer-for-students',
    'free-ai-tool-to-summarize-youtube-videos',
    'best-free-youtube-summarizer-tool',
    'youtube-summarizer-for-content-creators',
    'youtube-summarizer-for-lectures',
    'youtube-summarizer-with-timestamps',
    'youtube-summarizer-for-business-webinars',
    'youtube-summarizer-for-podcast-transcripts',
    'generate-blog-posts-from-youtube-summary',
    'convert-youtube-video-to-blog-post-summary',
    'youtube-summarizer-for-newsletter-content',
    'chrome-extension-to-summarize-youtube-videos',
    'ios-app-to-summarize-youtube-videos',
    'android-app-to-summarize-youtube-videos',
    'youtube-summarizer-mobile-app',
    'youtube-summarizer-with-bullet-points',
    'online-youtube-video-summary-generator',
    'free-youtube-video-summary-generator',
    'free-youtube-transcript-summary-tool',
    'youtube-transcript-summarizer-for-research',
    'summarize-youtube-tutorials-for-study',
    'youtube-summarizer-with-multi-language-support',
    'translate-and-summarize-youtube-videos',
    'summarize-youtube-videos-in-chinese-language',
    'youtube-summarizer-for-spanish-videos',
    'youtube-summarizer-for-french-videos',
    'youtube-summarizer-with-qa',
    'top-5-free-ai-tools',
    'ai-tool-to-summarize-academic-youtube-videos',
    'youtube-summarizer-for-script-writing',
    'youtube-summarizer-with-chapter-breakdown',
    'summarize-government-hearings-on-youtube',
    'youtube-summarizer-for-meeting-recordings',
    'summarize-youtube-interviews-for-market-research',
    'youtube-video-summarizer-for-training-videos',
    'youtube-summarizer-for-investor-videos',
    'summarize-corporate-presentations-on-youtube',
    'youtube-summarizer-for-legal-depositions',
    'youtube-summarizer-for-academic-research-papers',
    'students-youtube-summaries',
    'online-free-youtube-summarizer-with-translation',
    'youtube-summarizer-with-mind-map-output',
    'recipe-video-summary-cook-without-watching',
    'business-video-summaries-for-executives',
    'ai-video-summary-stay-updated-on-automation',
    'stock-market-video-summary-for-investors',
    'personal-finance-videos-get-the-tl-dr',
    'photography-tutorial-summaries-learn-the-techniques',
    'youtube-summarizer-for-doctors-and-medical-professionals',
    'youtube-summarizer-for-lawyers',
    'youtube-summarizer-for-teachers',
    'youtube-summarizer-for-journalists',
    'youtube-summarizer-for-entrepreneurs',
    'youtube-summarizer-for-marketers',
    'youtube-summarizer-for-researchers',
    'youtube-summarizer-for-hr-professionals',
    'how-to-use-youtube-summaries-for-note-taking',
    'youtube-summarizer-vs-manual-notes',
    'how-accurate-are-youtube-video-summaries',
    'youtube-summarizer-for-language-learning',
    'youtube-summarizer-for-remote-workers',
    'how-to-summarize-ted-talks',
    'youtube-summarizer-for-product-managers',
    'youtube-summarizer-for-data-analysts',
    'youtube-summarizer-for-fitness-coaches',
    'what-is-a-youtube-summarizer',
    'youtube-summarizer-for-podcasters',
    'youtube-summarizer-for-sales-teams',
    'youtube-summary-for-book-reviews',
    'youtube-summarizer-for-nonprofits',
    'youtube-summarizer-for-real-estate-professionals',
    'youtube-summarizer-for-engineers',
    'youtube-summarizer-for-designers',
    'youtube-video-too-long-how-to-get-key-points',
    'summarize-youtube-without-watching',
    'save-time-on-youtube-with-ai',
    'youtube-summarizer-for-youtube-shorts',
    'youtube-summarizer-api',
    'youtube-summarizer-privacy-and-security',
    'youtube-summarizer-for-high-school-students',
    'youtube-summarizer-for-phd-students',
    'youtube-summarizer-for-university-students',
    'youtube-summarizer-for-news-consumption',
    'best-free-youtube-summarizers-no-subscription-2026',
    'eightify-vs-ytsummarizer-which-youtube-summarizer-is-worth-it',
    'how-to-summarize-youtube-watch-later-backlog',
    'gaming-guide-video-summaries-level-up-faster',
    'language-learning-video-summaries-master-languages-faster',
    'fitness-workout-video-summaries-get-results-faster',
    'how-to-summarize-youtube-shorts-get-the-key-points-in-seconds',
    'summarize-instagram-reels-and-tiktok-videos-instantly-with-ai',
    'summarize-twitch-vods-and-live-streams-never-miss-important-moments',
  ]

  const blogPosts = posts.map((slug) => ({
    url: `${baseUrl}/blog/${slug}`,
    lastModified: new Date('2026-03-16'),
    changeFrequency: 'monthly' as const,
    priority: 0.8,
  }))

  return [
    {
      url: baseUrl,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 1,
    },
    ...blogPosts,
  ]
}
